GET http://localhost:3000/api/v1/shorteners

###

POST http://localhost:3000/api/v1/shorteners
Content-Type: application/json
Accept: application/json

{
  "shortener": {
    "url": "https://google.com"
  }
}